---
- :name: google_oauth2
  :data:
    :client_id: 16
    :redirect_uri: http://localhost:3000
    :issuer: http://localhost:3000
    :client_options:
      :site: http://localhost:3000
      :redirect_uri: http://localhost:3000
      :authorization_endpoint: http://localhost:3000
      :token_endpoint: http://localhost:3000
      :user_info_endpoint: http://localhost:3000
